'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Quality_SystemEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Quality_SystemEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblBookDoc() As DbSet(Of tblBookDoc)
    Public Overridable Property tblCarPar() As DbSet(Of tblCarPar)
    Public Overridable Property tblCause() As DbSet(Of tblCause)

End Class
