'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBookDoc
    Public Property BookNo As String
    Public Property Name As String
    Public Property BookDate As Nullable(Of Date)
    Public Property Depart As String
    Public Property Sys As String
    Public Property Type As String
    Public Property UseName As String
    Public Property StatusDoc As String
    Public Property Userby As String
    Public Property UserDate As Nullable(Of Date)
    Public Property Status As Nullable(Of Integer)

End Class
