'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCarPar
    Public Property carno As String
    Public Property cartype As Nullable(Of Integer)
    Public Property depprob As String
    Public Property manager As String
    Public Property carstate As Nullable(Of Integer)
    Public Property carstatus As String
    Public Property cardetail As String
    Public Property auditor As String
    Public Property recdate As Nullable(Of Date)
    Public Property qmr As String
    Public Property qmrrecdate As Nullable(Of Date)
    Public Property causeprob As String
    Public Property protectprob As String
    Public Property auditee As String
    Public Property managerrespon As String
    Public Property qmrrespon As String
    Public Property deadline As Nullable(Of Date)
    Public Property managerresdate As Nullable(Of Date)
    Public Property qmrresdate As Nullable(Of Date)
    Public Property followstate As Nullable(Of Integer)
    Public Property followdetail As String
    Public Property followby As String
    Public Property followdate As Nullable(Of Date)
    Public Property qmrclose As String
    Public Property closeremark As String
    Public Property qmrclosedate As Nullable(Of Date)
    Public Property approvestatus As Nullable(Of Integer)

End Class
